### ISSUE TITLE
Pi Zero

### ISSUE THREAD

**Issue by xied75** [alexellis/docker-arm#1]
:100: 

Is that possible to have a single page instruction as on how to do everything on a Zero?

**Comment by alexellis** [comment]
@xied75 you can find all the instructions in the Linux User and Developer's magazine article / PDF.

How far have you got and what do you want to get working? Just Docker or Swarm, too?

For Docker alone.. 
- You need to install [Arch Linux ARM](https://archlinuxarm.org/platforms/armv6/raspberry-pi) on your Raspberry PI Zero. 
- Install the Docker package `pacman -Syu docker`
- Then you can run `systemctl start docker` and start using the [images](https://github.com/alexellis/docker-arm/tree/master/images/armv6) available in the repository.

Let me know how you get on.

If in need of documentation on Docker itself try out the [fast track DockerLabs material](http://blog.alexellis.io/dockerlabs/)

**Comment by xied75** [comment]
@alexellis Thanks for the fast reply. I shall try it asap and report back.

Just one more quick question: must it be Arch? Can stock raspbian work?

**Comment by alexellis** [comment]
@xied75 if you'd like to work with this repository/tutorial, then yes. Once up and running you can run Raspbian or a Raspbian-like image inside Docker.

**Comment by alexellis** [comment]
@xied75 tried this out today and the docker package for the PI Zero works perfectly out of the box, but it is a bit slow on the underpowered machine.
